11. Python&Django/goodreads/books/urls.py
from django.urls import path
from books.views import BooksListView, BookDetailView, AddReviewView, EditReviewView, \
  ConfirmDeleteReviewView, DeleteReviewView

app_name = 'books'
urlpatterns = [
  path('', BooksListView.as_view(), name='list'),
  path('<int:id>/', BookDetailView.as_view(), name='detail'),
  path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews'),
  path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name='edit-review'),
  path('<int:book_id>/reviews/<int:review_id>/delete/confirm/', ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
  path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(), name='delete-review'),
]

11. Python&Django/goodreads/books/models.py
from django.db import models
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

class Book(models.Model):
  title = models.CharField(max_length=200)
  description = models.TextField()
  isbn = models.CharField(max_length=17)
  cover = models.ImageField(default='default_cover.png')

  def __str__(self):
    return self.title

class Author(models.Model):
  first_name = models.CharField(max_length=100)
  last_name = models.CharField(max_length=100)
  email = models.EmailField()
  bio = models.TextField()

  def full_name(self):
    return f"{self.first_name} {self.last_name}"

  def __str__(self):
    full_name = f"{self.first_name} {self.last_name}"
    return full_name

class BookAuthor(models.Model):
  book = models.ForeignKey(Book, on_delete=models.CASCADE)
  author = models.ForeignKey(Author, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"

class BookReview(models.Model):
  user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
  book = models.ForeignKey(Book, on_delete=models.CASCADE)
  comment = models.TextField()
  stars_given = models.IntegerField( validators=[MinValueValidator(0), MaxValueValidator(5)] )
  created_at = models.DateTimeField(default=timezone.now)

  def __str__(self):
    return f"{self.stars_given} stars for {self.book.title} by {self.user.username}"

11. Python&Django/goodreads/books/forms.py
from django import forms
from books.models import BookReview

class BookReviewForm(forms.ModelForm):
  stars_given = forms.IntegerField(min_value=1, max_value=5)

  class Meta:
    model = BookReview
    fields = ('comment' ,'stars_given')

11. Python&Django/goodreads/books/views.py
from django.shortcuts import render
from django.views import View
from books.models import Book, BookReview
from django.views import generic
from django.core.paginator import Paginator
from books.forms import BookReviewForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib import messages

# class BooksListView(generic.ListView):
#   template_name = 'books/list.html'
#   queryset = Book.objects.all()
#   context_object_name = 'books'
#   paginate_by = 3


# class BookDetailView(generic.DetailView):
#   template_name = 'books/detail.html'
#   pk_url_kwarg = 'id'
#   model = Book
#   context_object_name = 'book'


class BookDetailView(View):
  def get(self, request, id):
    book = Book.objects.get(id=id)
    review_form = BookReviewForm()
    context = {
      'book': book,
      "review_form": review_form,
    }
    return render(request, 'books/detail.html', context)


class BooksListView(View):
  def get(self, request):
    books = Book.objects.all().order_by('id')

    search_query = request.GET.get('q', '')
    if search_query:
      books = books.filter(title__icontains=search_query)

    page_size = request.GET.get('page_size', 4)
    paginator = Paginator(books, page_size)
    page_num = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_num)
    context = {
      'page_obj': page_obj,
      'search_query': search_query
    }
    return render(request, 'books/list.html', context)


class AddReviewView(LoginRequiredMixin, View):
  def post(self, request, id):
    book = Book.objects.get(id=id)
    review_form = BookReviewForm(data=request.POST)

    if review_form.is_valid():
      BookReview.objects.create(
        book=book,
        user=request.user,
        stars_given=review_form.cleaned_data['stars_given'],
        comment=review_form.cleaned_data['comment'],
      )
      return redirect(reverse('books:detail', kwargs={'id': book.id}))

    context = {
      'book': book,
      "review_form": review_form,
    }
    return render(request, 'books/detail.html', context)

class EditReviewView(LoginRequiredMixin, View):
  def get(self, request, book_id, review_id):
    book = Book.objects.get(id=book_id)
    review = book.bookreview_set.get(id=review_id)
    review_form = BookReviewForm(instance=review)
    context = {
      'book': book,
      'review': review,
      'review_form': review_form,
    }
    return render(request, 'books/edit_review.html', context)

  def post(self, request, book_id, review_id):
    book = Book.objects.get(id=book_id)
    review =  book.bookreview_set.get(id=review_id)
    review_form = BookReviewForm(instance=review, data=request.POST)

    if review_form.is_valid():
      review_form.save()
      return redirect(reverse('books:detail', kwargs={'id': book.id}))
    else:
      context = {
      'book': book,
      'review': review,
      'review_form': review_form,
    }
    return render(request, 'books/edit_review.html', context)

class ConfirmDeleteReviewView(LoginRequiredMixin, View):

  def get(self, request, book_id, review_id):
    book = Book.objects.get(id=book_id)
    review = book.bookreview_set.get(id=review_id)
    context = {
      'book': book,
      'review': review
    }
    return render(request, 'books/confirm_delete_review.html', context)

class DeleteReviewView(LoginRequiredMixin, View):

  def get(self, request, book_id, review_id):
    book = Book.objects.get(id=book_id)
    review = book.bookreview_set.get(id=review_id)
    review.delete()
    messages.success(request, "You have successully deleted review.")
    return redirect(reverse('books:detail', kwargs={'id': book.id}))

11. Python&Django/goodreads/books/templates/books/confirm_delete_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Confirm Delete Review {% endblock %}

{% block content %}
<h2 class="mb-3">Confirm Delete Review</h2>

<div class="row my-5">
  <div class="col-12">
      <p>Are you sure you want to <b>delete</b> this review?</p>
      <p>
        <span><i>Book:</i> {{ book.title }} </span> <br>
        <span><i>Comment:</i> {{ review.comment }} </span> <br>
      </p>
      <div class="d-flex justify-content-start">
        <a href="{% url 'books:delete-review' book.id review.id %}" class="btn btn-success">Yes</a>
        &nbsp;
        <a href="{% url 'books:detail' book.id %}" class="btn btn-danger">No</a>
      </div>
  </div>
</div>
{% endblock %}

11. Python&Django/goodreads/books/templates/books/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Book Detail {% endblock %}

{% block content %}
<div class="d-flex gap-4">
  <div>
    <img class="book-cover" src="{{book.cover.url}}" alt="{{book.title}}">
  </div>
  <div>

    <h3>{{ book.title }}</h3>

    <p class="text-muted mb-1">
      Authored by
      {% for book_author in book.bookauthor_set.all %}
        <b class="fst-italic">
          {% if forloop.last %}
            {{ book_author.author.full_name }}
          {% else %}
            {{ book_author.author.full_name }},
          {% endif %}
        </b>
      {% endfor %}
    </p>

    <span class="text-muted">ISBN: {{ book.isbn }}</span>

    <p class="mt-3 text-justify-custom">{{ book.description }}</p>

  </div>
</div>

<div class="row my-5">
  <div class="col-12">
    <form method="post" action="{% url 'books:reviews' book.id %}">
      {% csrf_token %}
      {{ review_form | crispy }}
      <div class="d-flex justify-content-end">
        <button class="btn btn-success">Add review</button>
      </div>
    </form>
  </div>
</div>

{% if book.bookreview_set.exists %}
<div class="row mt-5">
  <div class="col-12">
    <h4>Reviews</h4>
    <hr>
  </div>
  {% for review in book.bookreview_set.all %}
  <div class="col-12 mb-5">
    <div class="d-flex gap-3">
      <div class="d-flex gap-2 justify-align-center">
        <div>
          <img class="rounded-circle user-avatar" src="{{ review.user.avatar.url }}" alt="{{ review.user.username }}">
        </div>
      </div>
      <div>
        <p>
          <b>{{ review.user.username | capfirst }}</b> rated it {{ review.stars_given }} stars <span class="fw-lighter">{{ review.created_at }}</span>
          {% if review.user == request.user %}
          <a href="{% url 'books:edit-review' book.id review.id %}" class="btn btn-sm btn-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16"> <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708z"/> </svg>
            <!-- <span>Update</span> -->
          </a>
          <a href="{% url 'books:confirm-delete-review' book.id review.id %}" class="btn btn-sm btn-danger">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16"> <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/> <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/> </svg>
            <!-- <span>Delete</span> -->
          </a>
          {% endif %}
        </p>
        <p class="mb-2 text-muted fs-6">{{ review.comment }}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endif %}

{% endblock %}

11. Python&Django/goodreads/books/templates/books/edit_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Review {% endblock %}

{% block content %}
<h2 class="mb-3">Edit Review</h2>

<div class="row my-5">
  <div class="col-12">
    <form method="post" action="{% url 'books:edit-review' book.id review.id %}" >
      {% csrf_token %}
      {{ review_form | crispy }}
      <div class="d-flex justify-content-end">
        <button class="btn btn-success">Save</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

11. Python&Django/goodreads/books/templates/books/list.html
{% extends 'base.html' %}
{% block title %} Books {% endblock %}

{% block content %}

{% if page_obj %}

<div class="row mb-5">
  <div class="col-4">
    <form class="d-flex" role="search" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{search_query}}"/>
        <button class="btn btn-success" type="submit">Search</button>
      </form>
  </div>
</div>

<div class="d-flex justify-content-between align-items-center">

  <h2 class="mb-3">Books</h2>

  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {# Previous tugmasi faqat birinchi sahifada emasligida ko‘rinadi #}
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {# Sahifa raqamlari #}
      {% for num in page_obj.paginator.page_range %}
        {% if num == 1 or num == page_obj.paginator.num_pages %}
          {% if num == page_obj.number %}
            <li class="page-item active"><span class="page-link">{{ num }}</span></li>
          {% else %}
           <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
          {% endif %}
          {% elif num >= page_obj.number|add:"-2" and num <= page_obj.number|add:"2" %}
          {% if num == page_obj.number %}
          <li class="page-item active"><span class="page-link">{{ num }}</span></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
          {% endif %}
        {% elif num == page_obj.number|add:"-3" or num == page_obj.number|add:"3" %}
          <li class="page-item disabled"><span class="page-link">...</span></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}
    </ul>
  </nav>

</div>


<div class="row">
  {% for book in page_obj.object_list %}
  <div class="col-12 mb-4">
    <div class="card">
      <div class="card-header">
        <span class="text-muted">ISBN: {{book.isbn}}</span>
      </div>
      <div class="card-body d-flex gap-3">
        <div>
          <img src="{{book.cover.url}}" alt="{{book.title}}" style="width: 200px;">
        </div>
        <figure>
          <blockquote class="blockquote">
            <a href="{% url 'books:detail' book.id %}" class="link-offset-2 link-underline link-underline-opacity-0"
              title="{{ book.title }}">{{ book.title }}</a>
          </blockquote>
          <figcaption class="blockquote-footer">
            {{book.description}}
          </figcaption>
        </figure>
      </div>
    </div>
  </div>
  {% endfor %}

</div>

{% else %}

No books found.

{% endif %}

{% endblock %}