11. Python&Django/goodreads/api/urls.py
# from django.urls import path
# from api.views import BookReviewDetailAPIView, BookReviewListAPIView

# app_name = 'api'
# urlpatterns = [
#     path('reviews/', BookReviewListAPIView.as_view(), name="book-reviews-list"),
#     path('reviews/<int:id>/', BookReviewDetailAPIView.as_view(), name="book-detail-review"),
# ]

from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name = 'api'

router = DefaultRouter()
router.register(r'reviews', BookReviewsViewSet, basename='reviews')
urlpatterns = router.urls

11. Python&Django/goodreads/books/urls.py
from django.urls import path
from books.views import BooksListView, BookDetailView, AddReviewView, EditReviewView, \
  ConfirmDeleteReviewView, DeleteReviewView

app_name = 'books'
urlpatterns = [
  path('', BooksListView.as_view(), name='list'),
  path('<int:id>/', BookDetailView.as_view(), name='detail'),
  path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews'),
  path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name='edit-review'),
  path('<int:book_id>/reviews/<int:review_id>/delete/confirm/', ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
  path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(), name='delete-review'),
]

11. Python&Django/goodreads/config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from .views import index, home_page

urlpatterns = [
    path('', index, name="index"),
    path('home/', home_page, name="home"),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),

    path('api-auth/', include('rest_framework.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

11. Python&Django/goodreads/users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, \
     LogoutView, ProfileUpdateView

app_name = "users"

urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('profile/edit/', ProfileUpdateView.as_view(), name="profile-edit"),
]

11. Python&Django/goodreads/templates/base.html
{% load static %}
{% url 'home' as home_url %}
{% url 'books:list' as books_list_url %}
{% url 'users:profile' as user_profile_url %}
{% url 'users:profile-edit' as profile_edit_url %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}GoodreadsClone{% endblock %}</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
</head>
<!-- Custom CSS -->
 <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">

<body>

  <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;" data-bs-theme="light">
    <div class="container">

      <a class="navbar-brand" href="{% url 'index' %}"><b>Goodreads</b>Clone</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {% if request.path == home_url %} active {% endif %}" aria-current="page" href="{{ home_url }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == books_list_url %} active {% endif %}" aria-current="page" href="{{ books_list_url }}">Books</a>
          </li>
        </ul>

        <div>
          {% if request.user.is_authenticated %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle {% if request.path == user_profile_url or request.path == profile_edit_url %} active {% endif %}" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                {{ request.user.username | capfirst }}
              </a>
              <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="{{ user_profile_url }}">Profile</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>

              </ul>
            </li>
          </ul>
          {% else %}
          <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Login</a>
          {% endif %}
        </div>

      </div>
    </div>
  </nav>

  <div class="container mt-2">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
  </div>

  <div class="container my-5">
    {% block content %}
    {% endblock %}
  </div>

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
    crossorigin="anonymous"></script>
</body>

</html>

11. Python&Django/goodreads/templates/home.html
{% extends 'base.html' %}

{% block title %}Home Page {% endblock %}

{% block content %}

  <div class="d-flex justify-content-between align-items-center">

  <h2 class="mb-3">All Reviews</h2>

  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {# Previous tugmasi faqat birinchi sahifada emasligida ko‘rinadi #}
      {% if page_object.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_object.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {# Sahifa raqamlari #}
      {% for num in page_object.paginator.page_range %}
        {% if num == 1 or num == page_object.paginator.num_pages %}
          {% if num == page_object.number %}
            <li class="page-item active"><span class="page-link">{{ num }}</span></li>
          {% else %}
           <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
          {% endif %}
          {% elif num >= page_object.number|add:"-2" and num <= page_object.number|add:"2" %}
          {% if num == page_object.number %}
          <li class="page-item active"><span class="page-link">{{ num }}</span></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
          {% endif %}
        {% elif num == page_object.number|add:"-3" or num == page_object.number|add:"3" %}
          <li class="page-item disabled"><span class="page-link">...</span></li>
        {% endif %}
      {% endfor %}
      {% if page_object.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_object.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}
    </ul>
  </nav>

</div>

  <div class="posts-content">
    <div class="row">
      {% for review in page_object %}
        <div class="col-lg-6">
            <div class="card mb-4">
              <div class="card-body">
                <div class="media mb-3">
                  <img src="{{ review.user.avatar.url }}" class="d-block ui-w-40 rounded-circle" alt="{{ review.user.username }}">
                  <div class="media-body ml-3">
                    <span><b>{{ review.user.username | capfirst }}</b> rated this book {{ review.stars_given }} stars</span>
                    <div class="text-muted small">{{ review.created_at | timesince }}</div>
                  </div>
                </div>

                <p>
                  {{ review.comment|truncatechars:300 }}
                </p>
                <img class="home-book-cover" src="{{ review.book.cover.url }}" alt="{{ review.book.title }}">
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

11. Python&Django/goodreads/templates/index.html
{% extends 'base.html' %}
{% load tz %}

{% block content %}
<div class="card text-center">
  <div class="card-header">{% now "Y-m-d" %}</div>
  <div class="card-body">
    <p class="fs-2 mb-1"><b>Goodreads</b>Clone</p>
    <p class="fs-4 mt-1"> Meet your next favorite book. </p>
    <a href="{% url 'books:list' %}" class="btn btn-primary">Go books</a>
  </div>
  <div class="card-footer text-body-secondary">{% now "H:i" %}</div>
</div>
{% endblock %}