11. Python&Django/goodreads/users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, \
     LogoutView, ProfileUpdateView

app_name = "users"

urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('profile/edit/', ProfileUpdateView.as_view(), name="profile-edit"),
]

11. Python&Django/goodreads/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
  avatar = models.ImageField(default='default_avatar.jpg', blank=True)

11. Python&Django/goodreads/users/forms.py
from django import forms
from users.models import CustomUser

class UserCreateForm(forms.Form):
  username = forms.CharField(max_length=150)
  email = forms.EmailField()
  first_name = forms.CharField(max_length=150)
  last_name = forms.CharField(max_length=150)
  password = forms.CharField(max_length=128)
  # avatar = forms.ImageField()

  def save(self):
    username = self.cleaned_data['username']
    first_name = self.cleaned_data['first_name']
    last_name = self.cleaned_data['last_name']
    email = self.cleaned_data['email']
    password = self.cleaned_data['password']
    user = CustomUser.objects.create(
      username=username,
      first_name=first_name,
      last_name=last_name,
      email=email,
      )
    user.set_password(password)
    user.save()
    return user

class UserLoginForm(forms.Form):
  username = forms.CharField(max_length=150)
  password = forms.CharField(max_length=128)

class UserUpdateForm(forms.ModelForm):
  class Meta:
    model = CustomUser
    fields = ('username', 'first_name', 'last_name', 'email', 'avatar')

11. Python&Django/goodreads/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm
from users.forms import UserCreateForm, UserUpdateForm
from django.contrib import messages

class RegisterView(View):
  def get(self, request):
    create_form = UserCreateForm()
    context = {
      "form": create_form
    }
    return render(request, 'users/register.html', context)

  def post(self, request):
    create_form = UserCreateForm(data=request.POST)
    if create_form.is_valid():
      create_form.save()
      return redirect('users:login')
    else:
      context = { "form": create_form }
      return render(request, 'users/register.html', context)

class ProfileView(LoginRequiredMixin, View):
  def get(self, request):
    context = { 'user': request.user }
    return render(request, 'users/profile.html', context)

class LoginView(View):
  def get(self, request):
    login_form = AuthenticationForm()
    return render(request, 'users/login.html', {"login_form": login_form})

  def post(self, request):
    login_form = AuthenticationForm(data=request.POST)
    if login_form.is_valid():
      user = login_form.get_user()
      login(request, user)
      messages.success(request, 'You have successfully logged in.')
      return redirect('books:list')
    else:
      return render(request, 'users/login.html', {"login_form": login_form})

class LogoutView(LoginRequiredMixin, View):
  def get(self, request):
    logout(request)
    messages.info(request, 'You have successfully logged out.')
    return redirect('index')

class ProfileUpdateView(LoginRequiredMixin, View):
  def get(self, request):
    user_update_form = UserUpdateForm(instance=request.user)
    context = {
      'form': user_update_form
    }
    return render(request, 'users/profile_edit.html', context)

  def post(self, request):
    user_update_form = UserUpdateForm(
      instance=request.user,
      data=request.POST,
      files=request.FILES
      )
    if user_update_form.is_valid():
      user_update_form.save()
      messages.success(request, 'You have seccessfully update your profile.')
      return redirect('users:profile')

    return(request, 'users/update_edit.html', {'form': user_update_form})

11. Python&Django/goodreads/users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Login {% endblock %}

{% block content %}
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-6">
        <h2 class="mb-3">Login</h2>
        <form class="uniForm" method="POST" action="{% url 'users:login' %}">
          {% csrf_token %}
          {{ login_form | crispy }}
          <p>Don't have an account? <a class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'users:register' %}">Register here</a>.</p>
          <button class="btn btn-primary" type="submit">Submit</button>
        </form>
      </div>
    </div>
{% endblock %}

11. Python&Django/goodreads/users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock %}

{% block content %}
<div class="card shadow-sm" style="max-width: 540px; margin: 0 auto;">
  <div class="row g-0">
    <div class="col-md-4 p-3 text-center">
      <img src="{{ user.avatar.url }}" class="rounded-circle img-thumbnail" alt="user_avatar">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title d-flex justify-content-between align-items-center">
          <b>{{ user.first_name }} {{ user.last_name }}</b>
          <a href="{% url 'users:profile-edit' %}" class="btn btn-sm btn-outline-primary">Edit</a>
        </h5>
        <div class="mt-4">
          <span class=" text-muted"> <b>Username:</b> {{ user.username }} </span>
          <br>
          <span class=" text-muted"> <b>Email:</b> {{ user.email }} </span>
          <br>
          <span class=" text-muted"> <b>Joined:</b> {{ user.date_joined | date:"F j, Y" }} </span>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

11. Python&Django/goodreads/users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Profile edit {% endblock %}

{% block content %}

<div class="row d-flex justify-content-center align-items-center">
  <div class="col-6">

    <h2 class="mb-3">Edit Profile</h2>

    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form | crispy}}
      <button class="btn btn-primary" type="submit">Save changes</button>
    </form>

  </div>
</div>

{% endblock %}

11. Python&Django/goodreads/users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Register {% endblock %}

{% block content %}
<div class="row d-flex justify-content-center align-items-center">
  <div class="col-6">

    <h2 class="mb-3">Register page</h2>

    <form method="POST" action="{% url 'users:register' %}">
      {% csrf_token %}
      {{ form | crispy }}
      <button class="btn btn-primary" type="submit">Submit</button>
    </form>

  </div>
</div>
{% endblock %}